import { test, expect, chromium } from '@playwright/test';
import { createHash } from 'node:crypto';
import { resolve } from 'node:path';
import { mkdtemp, rm, cp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';

test('Gemini main tab, automatic reload preparation, cache reuse, expiry and fallback',async()=>{
  test.setTimeout(60000);
  const testRoot=await mkdtemp(resolve(tmpdir(),'formly-gemini-'));
  const path=resolve(testRoot,'extension'),profile=resolve(testRoot,'profile');
  await cp(resolve('dist'),path,{recursive:true});
  // Headless Chrome cannot operate its native permission bubble. Pregrant site access in this disposable test copy only.
  const manifest=JSON.parse(await readFile(resolve(path,'manifest.json'),'utf8'));
  manifest.host_permissions.push('http://*/*','https://*/*');
  await writeFile(resolve(path,'manifest.json'),JSON.stringify(manifest));
  const context=await chromium.launchPersistentContext(profile,{channel:'chromium',headless:true,args:['--enable-unsafe-extension-debugging',`--disable-extensions-except=${path}`,`--load-extension=${path}`]});
  try {
    const id=createHash('sha256').update(path).digest('hex').slice(0,32).replace(/[0-9a-f]/g,c=>String.fromCharCode(97+parseInt(c,16)));
    const worker=context.serviceWorkers()[0] || await context.waitForEvent('serviceworker');
    // Mock only Google's responses. Extension messaging, storage, alarms, injection and action handling are real.
    await worker.evaluate(()=>{
      const state=globalThis as typeof globalThis & {testRequests:unknown[];testFail:boolean};state.testRequests=[];state.testFail=false;
      globalThis.fetch=async(input,init)=>{
        const url=String(input);
        if(!url.startsWith('https://generativelanguage.googleapis.com/')) throw new Error('Unexpected request');
        if(!init?.body) return new Response(JSON.stringify({models:[{name:'models/gemini-3.8-flash',supportedGenerationMethods:['generateContent']}]}));
        if(state.testFail) return new Response('Quota exceeded',{status:429});
        const body=JSON.parse(String(init.body));const metadata=JSON.parse(body.contents[0].parts[0].text);
        state.testRequests.push(metadata);
        const words=['Cedar','Maple','Willow','Birch','Oak','Pine','Elm','Ash','Palm','Olive'];
        const fields=metadata.fields.map((field:{id:string;type:string})=>({id:field.id,values:field.type==='datetime-local'?words.map((_,i)=>`2026-10-${String(i+10).padStart(2,'0')}T09:30`):words}));
        return new Response(JSON.stringify({candidates:[{content:{parts:[{text:JSON.stringify({fields})}]}}]}));
      };
    });
    const options=await context.newPage();await options.goto(`chrome-extension://${id}/index.html`);
    await expect(options.getByRole('button',{name:'Gemini',exact:true})).toHaveClass('selected');
    await expect(options.getByLabel('API key',{exact:true})).toBeEnabled();
    await options.getByLabel('API key',{exact:true}).fill('fake-key-for-local-tests');
    await expect(options.getByLabel('Cache expiry (minutes)',{exact:true})).toHaveValue('5');
    await options.getByLabel('Cache expiry (minutes)',{exact:true}).fill('0');
    await expect(options.getByRole('button',{name:'Save expiry',exact:true})).toBeDisabled();
    await options.getByLabel('Cache expiry (minutes)',{exact:true}).fill('12');
    await options.getByRole('button',{name:'Save expiry',exact:true}).click();
    await expect(options.getByRole('status')).toContainText('Cache expiry saved: 12 minutes');
    // Cache preferences are independent of unsaved credentials and need no website permission.
    expect(await worker.evaluate(async()=>(await chrome.storage.local.get('gemini')).gemini.apiKey)).toBe('');
    await expect(options.getByLabel('API key',{exact:true})).toHaveValue('fake-key-for-local-tests');
    await options.getByRole('button',{name:'Test key',exact:true}).click();
    await expect(options.getByRole('status')).toContainText('Key accepted');
    await options.getByLabel('Use Gemini for unknown fields').check();
    await options.getByRole('button',{name:'Save settings',exact:true}).click();
    await expect(options.getByRole('status')).toContainText('Reload a website');
    await expect.poll(()=>worker.evaluate(()=>chrome.permissions.contains({origins:['http://*/*','https://*/*']}))).toBe(true);
    const website=await context.newPage();
    await website.addInitScript(()=>document.addEventListener('DOMContentLoaded',()=>{const field=document.querySelector<HTMLInputElement>('#project-code');if(field)field.value='Private entered value';const header=document.createElement('header');header.innerHTML='<input id=header-special value=Navigation><select id=header-region><option value=en>English</option><option value=fr>French</option></select>';document.body.prepend(header);}));
    await website.goto('http://127.0.0.1:5188/demo.html');
    const requests=()=>worker.evaluate(()=>(globalThis as typeof globalThis & {testRequests:unknown[]}).testRequests);
    await expect.poll(async()=>(await requests()).length).toBe(1);
    const remaining=await worker.evaluate(async()=>{
      const all=await chrome.storage.session.get(null);
      const batch=Object.entries(all).find(([key])=>key.startsWith('gemini-cache:'))![1];
      return batch.expiresAt-Date.now();
    });
    expect(remaining).toBeGreaterThan(11*60000);expect(remaining).toBeLessThanOrEqual(12*60000);
    await expect(website.locator('#project-code')).toHaveValue('Private entered value');
    await expect(website.locator('#first')).toHaveValue('');
    expect(JSON.stringify(await requests())).not.toContain('Private entered value');
    expect(JSON.stringify(await requests())).not.toContain('fake-key-for-local-tests');
    expect(JSON.stringify(await requests())).not.toContain('header-special');
    expect(JSON.stringify(await requests())).not.toContain('header-region');
    const cdp=await context.browser()!.newBrowserCDPSession();
    const {targetInfos}=await cdp.send('Target.getTargets',{filter:[{type:'tab',exclude:false},{exclude:true}]});
    const target=targetInfos.find(t=>t.url===website.url())!;
    await cdp.send('Extensions.triggerAction',{id,targetId:target.targetId});
    await expect.poll(()=>website.locator('#project-code').inputValue()).not.toBe('Private entered value');
    await expect(website.locator('#project-code')).toHaveValue('Cedar');
    await expect(website.locator('#header-special')).toHaveValue('Navigation');
    await expect(website.locator('#header-region')).toHaveValue('en');
    await expect(website.locator('#email')).not.toHaveValue('');
    await expect.poll(()=>worker.evaluate(async()=>{const all=await chrome.storage.session.get(null);return Object.entries(all).filter(([k])=>k.startsWith('gemini-cache:')).flatMap(([,v])=>Object.values(v.values as Record<string,string[]>)).some(v=>v.includes('Cedar'));})).toBe(false);
    await cdp.send('Extensions.triggerAction',{id,targetId:target.targetId});
    await expect(website.locator('#project-code')).toHaveValue('Maple');
    expect((await requests()).length).toBe(1);
    await website.reload();
    await expect(website.locator('#project-code')).toHaveValue('Private entered value');
    await cdp.send('Extensions.triggerAction',{id,targetId:target.targetId});
    await expect(website.locator('#project-code')).toHaveValue('Willow');
    expect((await requests()).length).toBe(1);
    await options.getByLabel('Cache expiry (minutes)',{exact:true}).fill('2');
    await options.getByRole('button',{name:'Save expiry',exact:true}).click();
    await expect(options.getByText('Cache expiry saved: 2 minutes. Previous suggestions cleared.')).toBeVisible();
    expect(await worker.evaluate(async()=>Object.keys(await chrome.storage.session.get(null)).filter(key=>key.startsWith('gemini-cache:')).length)).toBe(0);
    await options.reload();
    await expect(options.getByLabel('Cache expiry (minutes)',{exact:true})).toHaveValue('2');
    await expect(options.getByLabel('Use Gemini for unknown fields')).toBeChecked();
    await expect(options.getByLabel('API key',{exact:true})).toHaveValue('fake-key-for-local-tests');
    await website.reload();
    await expect.poll(async()=>(await requests()).length).toBe(2);
    const newRemaining=await worker.evaluate(async()=>Object.entries(await chrome.storage.session.get(null)).find(([key])=>key.startsWith('gemini-cache:'))![1].expiresAt-Date.now());
    expect(newRemaining).toBeGreaterThan(60000);expect(newRemaining).toBeLessThanOrEqual(2*60000);
    await worker.evaluate(async()=>{const all=await chrome.storage.session.get(null);for(const [key,value] of Object.entries(all))if(key.startsWith('gemini-cache:'))await chrome.storage.session.set({[key]:{...value,expiresAt:Date.now()-1}});});
    await options.evaluate(()=>chrome.runtime.sendMessage({type:'gemini:status'}));
    await expect.poll(()=>worker.evaluate(async()=>Object.keys(await chrome.storage.session.get(null)).filter(k=>k.startsWith('gemini-cache:')).length)).toBe(0);
    await website.reload();await expect.poll(async()=>(await requests()).length).toBe(3);
    await options.getByRole('button',{name:'Clear Gemini cache'}).click();
    await expect(options.getByText('Cached suggestions cleared.')).toBeVisible();
    await worker.evaluate(()=>{(globalThis as typeof globalThis & {testFail:boolean}).testFail=true;});
    await cdp.send('Extensions.triggerAction',{id,targetId:target.targetId});
    await expect(website.locator('#project-code')).toHaveValue(/^[A-Za-z]+$/);
    await expect.poll(()=>worker.evaluate(async()=>(await chrome.storage.session.get('geminiStatus')).geminiStatus)).toContain('quota');
    await options.reload();await expect(options.getByLabel('API key',{exact:true})).toHaveValue('fake-key-for-local-tests');
    await options.getByRole('button',{name:'Remove saved key',exact:true}).click();
    await expect(options.getByLabel('API key',{exact:true})).toHaveValue('');
    await expect(options.getByLabel('Use Gemini for unknown fields')).not.toBeChecked();
    await options.screenshot({path:'test-results/gemini-options.png',fullPage:true});
    await options.setViewportSize({width:360,height:800});
    await expect.poll(()=>options.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await options.screenshot({path:'test-results/gemini-mobile.png',fullPage:true});
  } finally {await context.close();await rm(testRoot,{recursive:true,force:true});}
});
